
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'US History'
tagline:          'from http://cnx.org/contents/a7ba2fb8-8925-4987-b182-5f4429d48daa@3.85 (CC-BY)'
url:              https://github.com/philschatz/us-history-book
origin:           http://cnx.org/contents/a7ba2fb8-8925-4987-b182-5f4429d48daa@3.85

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          3.85

bookviewer:       http://philschatz.com/book-viewer

